server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketng
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: false
security:
  jwt:
    secret-key: ticketng











    #spring.jackson.serialization.fail-on-empty-beans=false

